# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29574fb8d62262845656c2c97921c9525e9e26faf3b064efc710678fe1883a78bdbba42ad128089628b1edd8afb39ed866272ca59082fb8e535fd82e9acc10b5

test:
  secret_key_base: 696ef31950f638310a69cdbba4d527812651bed4daab179187179f447efda0a03e0d3daf032e84c023f315464c1707fe8498ba7416e3912a2be08cc44eda7502

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
